version: "3"
services:
   # web:
   #    build: api
   #    command: python ./main.py
   #    ports:
   #    - 8080:8080
   #    volumes:
   #    - ./api:/app
   #    depends_on:
   #      - db
   db:
      image: postgres
      restart: always
      environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_DB=report_designer
      ports:
         - 5433:5432
      volumes:
         - ./api/sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
